name: scrape
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url '${{ secrets.WEBSITE_URL }}/api/scraper' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
