name: scrape
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Call scraper API route
        run: |
          curl --request POST \
          --url '${{ secrets.WEBSITE_URL }}/api/scraper' \
          --header 'Authorization: ${{ secrets.SCRAPER_SECRET_KEY }}'
